.github/workflows/test.yaml
cmake/Cargo.cmake
cmake/FindRust.cmake
generator/src/main.rs
generator/src/subcommands/build_crate.rs

Adds RUSTUP_TOOLCHAIN option to select the backend toolchain via rustup.
Renames FindCargo to FindRust
Fixes #1

Unwrap proxy binaries and discover installed toolchains

---

.github/workflows/test.yaml
cmake/Cargo.cmake

Run gen-cmake from CMAKE_BINARY_DIR as expected

---

.github/workflows/test.yaml
CMakeLists.txt
cmake/Corrosion.cmake

Explicitly set Corrosion's link language to use already-found C++ compiler.

Test Linux Cross Compile

---

CMakeLists.txt
README.md
cmake/Corrosion.cmake
test/cpp2rust/CMakeLists.txt
test/rust2cpp/CMakeLists.txt

Renames add_crate -> corrosion_import_crate
Renames cargo_link_libraries -> corrosion_link_libraries

Prefix Corrosion functions with corrosion_

---

.github/workflows/test.yaml

- Use corrosion-rs/install-cmake instead of AndrewGaspar/install-cmake
- Replace `cmake -H` with `cmake -S` in CI

Minor CI improvements

---

RELEASES.md

Update Release notes with the latest changes.

Update Release notes

---

CMakeLists.txt
README.md
RELEASES.md

Bump the version number to v0.2.0 and create a tagged release.

Release v0.2.0

---

RELEASES.md

Prepare for a bugfix release for v0.2

Update Release notes for v0.2.1

---

README.md
cmake/Corrosion.cmake
test/CMakeLists.txt
test/cargo_flags/CMakeLists.txt
test/cargo_flags/main.cpp
test/cargo_flags/rust/Cargo.toml
test/cargo_flags/rust/src/lib.rs

/closes #132
I was able to make additional arguments work, but I've seen a lot of things I don't understand the use of (e.g. the whole generator) so some things are probably missing.
Originally I named it FLAGS, but I guess ARGUMENTS, ARGS, or something else would be much more suitable and I'm open to any suggestions.

Pass additonal argument to cargo build

---

.github/workflows/test.yaml

Update wildcard to also match against stable/xyz branches.

CI: test PRs to all branches

---

.github/workflows/test.yaml
README.md
test/cpp2rust/CMakeLists.txt
test/cpp2rust/lib.cpp
test/cpp2rust/lib2.cpp
test/cpp2rust/path with space/lib3.cpp

- bump stable with commits before CMake minimum version increase
- enable CI for pull requests to stable

Backport to stable CI: test PRs to all branches

---

README.md
RELEASES.md
cmake/FindRust.cmake
test/rustflags/CMakeLists.txt

Backport two minor bugfix commits to `stable/v0.2` branch and release new patch release v0.2.2

Minor bugfix Release

---

RELEASES.md

Bugfix release based on `stable/v0.2` branch

Update Release notes for v0.2.2

---

.github/actions/setup_test/action.yaml
.github/workflows/test.yaml

- Makes it possible to easily define new jobs outside of the test matrix
- Update install-cmake to new version (nodejs16)
- Update actions/checkout to new version (nodejs16)

Reusable test workflow

---

.github/workflows/test.yaml

missed this one on the previous commit

CI: bump actions/checkout to v3

---

.github/actions/setup_test/action.yaml
.github/workflows/test.yaml

The action is unmaintained and dtolnays action seems much simpler.

CI: Replace actions-rs/toolchain

---

.github/workflows/test.yaml
test/CMakeLists.txt
test/multitarget/CMakeLists.txt
test/output directory/CMakeLists.txt

CI runtime for this PR is now slightly more than 6 minutes (was 9 minutes after previous optimizations)

CI: Run tests in parallel

---

cmake/CorrosionGenerator.cmake

the positional argument must come first

Fix NO_LINKER_OVERRIDE

---

cmake/FindRust.cmake

Findrust fixes

---

cmake/Corrosion.cmake

If an imported Rust target is only a static lib
it does not make sense to specify a linker or
link libraries into it, because the linker will not be invoked. Print a warning to inform the user of this likely unwanted behavior.
Since currently both cdylib and staticlib are conflated behind the same target (and this can't be solved before Rust 1.64) we omit the warning if a shared library is also built.

Warn when modifying linker options for static libs

---

cmake/Corrosion.cmake

Fix the artifact directory for custom json targets.
Fixes #315

Fix custom json targets

---

CMakeLists.txt
RELEASES.md
cmake/Corrosion.cmake
cmake/CorrosionGenerator.cmake
generator/Cargo.lock
generator/src/main.rs

Patch release mostly for the hostbuild fix.

Release v0.3.4

---

cmake/Corrosion.cmake
cmake/CorrosionGenerator.cmake
doc/src/usage.md
generator/src/main.rs
generator/src/subcommands/gen_cmake.rs
generator/src/subcommands/gen_cmake/target.rs
test/workspace/workspace/CMakeLists.txt

- Support LOCKED, FROZEN, IMPORTED_CRATES and FLAGS options with the legacy generator.
- Add a status message around building the legacy generator, to inform the user of what is going on.

Support more options with the legacy generator

---

cmake/Corrosion.cmake
doc/src/usage.md

 Update corrosion_import_crate documentation

---

cmake/Corrosion.cmake

It's much less verbose to just create the list of libs unconditionally, and later set it to empty if
NO_STD is set.
This code will likely anyway be removed
in the near future, but I still felt
like cleaning it up now.

Simplify NO_STD code

---

cmake/CorrosionGenerator.cmake

Add some information to the error message on common causes, a list of all packages there were found and print
the `CRATES` whitelist if it set.
It's a bit unfortunate that the CRATES whitelist is actually a whitelist for package names, but changing this is a
breaking change.
Closes #380

Improve error message if no package is imported

---

CMakeLists.txt
README.md
RELEASES.md
cmake/Corrosion.cmake
doc/src/quick_start.md
doc/src/setup_corrosion.md

Fixes an issue with multi-config generators, reported originally here: https://github.com/slint-ui/slint/pull/2807#issuecomment-1573945003

Fix regression in v0.4 and release bugfix

---

CMakeLists.txt
cmake/Corrosion.cmake
cmake/CorrosionGenerator.cmake
cmake/FindRust.cmake

- Log the Corrosion version with `DEBUG` verbosity.
- Add some log-context.

Some minor logging related additions

---

generator/Cargo.lock
generator/Cargo.toml

- Bump serde past problematic version with pre-compiled binaries
- Bump cargo-metadata.

Legacy Generator: Update dependencies

---

RELEASES.md

Release latest changes for v0.4 before master diverges from v0.4.

Update release notes for v0.4.3

---

.github/workflows/test.yaml

- Upgrade to windows-2022 for -gnu tests
- Upgrade to macos-13

CI: Maintainence

---

cmake/Corrosion.cmake

Don't set `AR` for `msvc` targets

---

RELEASES.md
cmake/Corrosion.cmake
cmake/CorrosionGenerator.cmake
generator/src/subcommands/gen_cmake/target.rs

Backport #437 windows hostbuild fix to v0.4

---

cmake/Corrosion.cmake

Fix hostbuild when crosscompiling to windows from a different OS.

Fix hostbuild when crosscompiling to windows

---

cmake/Corrosion.cmake

Update comments to clarify why BYPRODUCTS currently can't be used in the `_cargo-build-${target_name}` target.

Update comment regarding build byproducts

---

cmake/Corrosion.cmake

corrosion_link_libraries: Allow linking by full path and non-target library name

---

CMakeLists.txt
RELEASES.md
cmake/FindRust.cmake

Backports patches requested in #617

Release v0.5.2
