- .github/workflows/test.yaml
- README.md
- cmake/Corrosion.cmake
- cmake/FindRust.cmake
When defining `Rust_TOOLCHAIN`, looking up the
toolchain via `rustup` is prioritized.
When the user changes or sets `Rust_TOOLCHAIN`,
FindRust is re-evaluated.
A non-cache `Rust_TOOLCHAIN` is promoted to a
cache variable.
A toolchain shorthand (e.g. `stable` or `1.44.0` or
`nightly`) can now be specified to Rust_TOOLCHAIN
Options are now documented.
Fixes #37, #43
cc @lievenvanderheide
> Improvements for selecting a Rust toolchain

- cmake/Corrosion.cmake
Currently Corrosion cannot be used with the "Ninja Multi-Config" generator. This PR issues a hard failure to make this issue clear to users. See #50.
cc @humenda
> Issue a hard-error if Corrosion is used with the "Ninja Multi-Config" generator

- generator/Cargo.toml
Make sure corrosion works when it is checked out in a sub-directory of a repository with 
a Cargo.toml workspace
For example, in my case, My repository's root has both a Cargo.toml and a CMakeLists.txt,
and i'm using the `FetchContent` feature to check out corrosion.
However, this does not work with the common practice to put the build repository in a 
sub-directory of the source directory, otherwise the build fails with 
```
error: current package believes it's in a workspace when it's not:
current:   /foo/bar/build/_deps/corrosion-src/generator/Cargo.toml
workspace: /foo/bar/Cargo.toml
this may be fixable by adding `build/_deps/corrosion-src/generator` to the `workspace.members` array of the manifest located at: /foo/bar/Cargo.toml
Alternatively, to keep it out of the workspace, add the …
```
> Fix when used in a subdir of a workspace

- cmake/Corrosion.cmake
Ninja supports the concept of job pools so that cargo is not run in parallel.
Otherwise, we see a lot of
```
Blocking waiting for file lock on build directory
```
> Use JOB_POOL to avoid running cargo in parallel

- generator/src/main.rs
Otherwise, the user gets to see a nice panic message instead of
something short and actionable.
> If MANIFEST_PATH is unwrapped, it should be required.

- generator/src/main.rs
Again, a panic message is probably hard to read here.
> Get rid of unwrap() on cargo_metadata exec().

- cmake/Corrosion.cmake
This will make sure that ninja does not buffer all the output from cargo
so that the user can see cargo progress in the terminal as the build
proceeds.
> Use `USES_TERMINAL` instead of job pools

- cmake/Corrosion.cmake
- cmake/FindRust.cmake
- generator/src/subcommands/build_crate.rs
Commit 3c9ff60f51cac21fcd4add47c1a14da47fe1c02e introduced the feature
that host binaries can be built, which is done by omitting the
`--target` parameter to cargo. This however implies that the target host
directory is picked by cargo (for example `cargo/build/debug`) for these
builds, which ends up being shared with the corrosion build itself, as
that is built implicitly via `cargo run`. If there were any common
crates as dependencies, then those may end up being built with different
flags (for corrosion and for host builds of the project), resulting in
unnecessary rebuilds.
To fix this, this patch makes use of the internal knowledge about the
host target by always passing it again.
> Fix unnecessary rebuilds when using CORROSION_USE_HOST_BUILD

- cmake/FindRust.cmake
- test/config/FindRust/CMakeLists.txt
- test/config/FindRust/Test.cmake
CMake only allows creating alias targets once, otherwise it bails out with
CMake Error at thirdparty/corrosion/cmake/FindRust.cmake:330 (add_executable):
add_executable cannot create imported target "Rust::Rustc" because another
target with the same name already exists.
Allow using find_package(Rust) in several places by following the pattern of other
find modules, protecting with an if.
> Allow using FindRust.cmake several times

- CMakeLists.txt
The parameter ARCH_INDEPENDANT  to `write_basic_package_version_file`
is not available on cmake 3.13, but only starting with 3.14.
See the Documentation for [3.13 here](https://cmake.org/cmake/help/v3.13/module/CMakePackageConfigHelpers.html#command:write_basic_package_version_file)
and for [3.14 here](https://cmake.org/cmake/help/v3.14/module/CMakePackageConfigHelpers.html#command:write_basic_package_version_file)
This partially fixes the build on Debian 10 buster with the default Cmake v3.13.
I tested in a VM provisoned by Vagrant with the following Vagrantfile:
```
$dependency_script=<<-SCRIPT
echo "Start Provisioning"
apt update
apt install -y build-essential cmake git curl
SCRIPT
$user_dependency_script=<<-SCRIPT
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y …
```
> Partially fix build with CMake 3.13 on Debian 10

- cmake/FindRust.cmake
Some cargo versions shipped with rust nightlies seem to be reporting their version without the cargo prefix, e.g.:
```
$ cargo +nightly-2021-07-24 --version
1.55.0-nightly (cebef2951 2021-07-22)
```
This commit relaxes the parsing slightly by adding an elseif
condition that matches on the expression without the leading
`cargo `. It's not an elegant solution, but it works for now.
______________
This is just a quick workaround from my side, but I'm open to suggestions if you would like a more thorough fix.
> Relax Cargo version parsing

- cmake/FindRust.cmake
Motivation for this change is to be able to reuse the FindRust module in a more general setting to see if rust exists.
With this change, it should be able to be used by any other package and afterwards check Rust_FOUND of its existence.
Earlier a missing .cargo/bin/rustc would fail with
```
The system cannot find the file specified
CMake Error at corrosion/cmake/FindRust.cmake:171 (get_filename_component):
get_filename_component called with incorrect number of arguments
```
Now it prints a more descriptive errormessage, sets Rust_FOUND to false
and returns.
It also sets Rust_FOUND to true if a rust target is successfully created
> make FindRust gracefully fail if rustc not found

- .github/workflows/test.yaml
- generator/src/subcommands/gen_cmake/platform.rs
- Fix Building on Windows with Rust >= 1.57 by linking with Bcrypt.
- Test with MacOS 10.15 instead of `macos-latest`, since linking on MacOS 11 currently does not work. I don't have a mac, so I'm leaving it up to someone who has one to fix building on Macos 11.
#Closes 119
> Attempt to fix CI

- cmake/FindRust.cmake
Since using unstable features (typically) requires a nightly toolchain,
check by matching against the `-nightly` suffix of the rustc version and
export that information as a new flag `Rust_IS_NIGHTLY` to users.
A user could then conditionally enable unstable features, by selecting a
corresponding feature via corrosion.
It seems that currently variables such as `Rust_VERSION` are not documented, so I also did not add documentation for this new flag. Would you accept an MR that documents the `Rust_` variables that `FindRust.cmake` provides?
> Export flag to check if rustc is a nightly

- generator/Cargo.lock
- generator/Cargo.toml
- generator/src/subcommands/gen_cmake/platform.rs
- Bumps the dependencies of the Generator to the most recent versions
- `platforms` renamed some enums
- Since bitflags (dependency of clap) version 1.3 raises the MSRV to 1.46, specify bitflags as a direct dependency to prevent `cargo update` from updating bitflags beyond `1.2`.  `clap` specifies the required bitflags versions as `^1`.
> Bump dependencies 

- README.md
- cmake/FindRust.cmake
- Document the version related variables that corrosion (FindRust) provides
- Improve the Rust_IS_NIGHTLY variable by always defining it (allows testing wether corrosion is new enough to set this variable)
- Add variables to expose the LLVM version used by rust. Useful e.g. for cross-language lto, where you want to be sure that the llvm version on both sides matches.
> Improve documentation of Rust version related variables

- cmake/Corrosion.cmake
When adding multiple crates, add all of them to the cargo-clean target
> Correctly clean all the imported crates

- README.md
- cmake/Corrosion.cmake
- generator/src/subcommands/build_crate.rs
- generator/src/subcommands/gen_cmake.rs
- generator/src/subcommands/gen_cmake/target.rs
- test/CMakeLists.txt
- test/custom_profiles/CMakeLists.txt
- test/custom_profiles/main.cpp
- test/custom_profiles/rust/Cargo.toml
- test/custom_profiles/rust/src/lib.rs
Add the option to specify the cargo profile by optionally specifying
CARGO_PROFILE when importing a crate. Cargo profiles are specified on
the workspace level, so it makes sense to select this option with
corrosion_import_crate.
This can be useful for specifying e.g. a `release-with-dbg` or
`release-with-lto` profile etc, that the user can then conditionally
select.
We currently do appear to conditionally link some libraries, depending
on the CMake build mode. So if the user selects a profile that requires
libraries, that are only linked in a different CMake build mode, then
this may cause issues for them. But I would label that a configuration
issue, that can be improved separately if it turns out to be necessary.
> Add --profile support for rust >= 1.57

- CMakeLists.txt
- RELEASES.md
Corrosions version has never been changed yet. Still, new features are
being added, and it would be great to update the version number from
time to time so we can use `find_package` to require a minimal version
number if we need some new corrosion feature.
Therefor I propose to bump the corrosion version number to 0.1.0 and
bump the patch version regularly if new features / bugfixes are added,
and bump the minor for breaking changes, including an increase of the
minimum supported cmake or rust version.
I'm aware that there are still open issues in the Project Plan for v0.1, but I think that this shouldn't keep us from releasing a new version from time to time. 
Any opinions on this?
> Release corrosion v0.1.0

- CMakeLists.txt
- README.md
- cmake/Corrosion.cmake
- cmake/CorrosionGenerator.cmake
> Support parsing cargo metadata by string(JSON ...) for cmake >= 3.19

- cmake/Corrosion.cmake
The helper variable _CORROSION_CMAKE_GREATER_EQUAL_3_19 should have been
cached.
However, lets just get rid of it entirely, and simply use the CORROSION_EXPERIMENTAL_PARSER
variable. It is now forced off for CMake < 3.19 instead of just defaulting to off.
> Fix issue in detecting cmake version

- cmake/Corrosion.cmake
- test/envvar/CMakeLists.txt
- test/envvar/build.rs
Cargo build scripts may themselves build c-dependencies and may choose
the compiler by inspecting CC or CXX.
Thus we should pass the compiler that was set in CMake, or alternatively
that is set in the environment to cargo.
This allows the build script to select the same compiler.
Closes #85
> Set CC and CXX for cargo

- cmake/Corrosion.cmake
This commit is not extensively tested but at a first glance,
Ninja Multiconfig seems to work. I'll test this a bit more thoroughly at work tomorrow.
Closes #50
> Allow Ninja Multi-config for Cmake >= 3.20

- cmake/FindRust.cmake
With the Rust toolchain 1.44.1 the reported LLVM version is 9.0,
i.e. without a patch version.
> Improve LLVM version parsing robustness

- cmake/Corrosion.cmake
- integrator/src/lib.rs
- test/cpp2rust/CMakeLists.txt
- test/cpp2rust/lib2.cpp
- test/cpp2rust/path with space/lib3.cpp
- test/cpp2rust/rust/src/main.rs
We use `COMMAND_EXPAND_LISTS`, which also expands lists in generator
expressions. Therefore the values of the env variables will be space
seperated.
Closes #128
> Fix Integrator build script

- cmake/Corrosion.cmake
There was a small mistake with #154: when setting NO_STD, the `--no-default-libraries` switch was not passed to the cmake generator This MR fixes the issue.
> Do not include libraries with NO_STD

- CMakeLists.txt
CMAKE_INSTALL_FULL_<dir> generates an absolute path
> "typically by prepending the value of the CMAKE_INSTALL_PREFIX
variable."
That seems to basically be what we want to do anyway, so simplify the
install code and let CMake do the expansion to the absolute path.
> Improve installation step

- cmake/CorrosionConfig.cmake.in
A follow up to commit d82585496.
For the config file we should also let CMake do the handling of the path expansion.
> Improve installation step #2

- .github/workflows/test.yaml
- cmake/CorrosionGenerator.cmake
Fix Corrosion on macOS >=11 by adding the necessary link directory if
using the experimental parser. There is technical reason preventing
a backport to the older generator (except that the property
INTERFACE_LINK_DIRECTORIES requires CMake >= 3.13), so future work
could add support for older CMake versions.
For now I think its fine requiring a recent CMake version for recent
macOS versions.
Closes #104
> Fix macos-11 for CMake >= 3.19

- cmake/Corrosion.cmake
For Rust targets, Rust will invoke the linker and add (among others) the
-lSystem flag. This works fine for the default linker, but if we use a
custom linker (e.g. g++, or even /usr/bin/ld), then we must provide
that path to the System library.
Adding -L<path> to RUSTFLAGS works fine for regular libraries, but fails
for build-scripts (See https://github.com/rust-lang/cargo/issues/4423 )
because there is no way to set RUSTFLAGS for build scripts when
cross-compiling. This is mostly an issue because we always specify the
target, even when building for host, but that is already sufficient for
the RUSTFLAGS to not apply to the build-script-build.
Target specific RUSTFLAGS (i.e CARGO_TARGET_<triple>_RUSTFLAGS also
don't seem to affect buildscripts.
Setting LIBRARY_PATH=<path> applies to normal …
> Fix macos-11

- cmake/Corrosion.cmake
After commit 0b0b182f8d2e12a1558d12dc5aea15bc815c703b, cc-rs now invokes
the compiler found by CMake, for example
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
instead of
/usr/bin/cc
The latter uses the default SDK sysroot root as configured with xcode.
The latter requires either specifying --sysroot /path/to/sysroot (which
is what CMake does) or it falls back to using the SDKROOT environment
variable. Without a sysroot the compiler can't find standard includes.
This patch sets SDKROOT as environment variable to be set during cargo
invocation, to the same value that CMake passes to the compiler. That
way cc-rs won't need any additional flags.
cc #152
> Fix compilation of projects using cc-rs on macOS

- cmake/Corrosion.cmake
There may be no linker preference if the user has no language enabled
in CMake, or no specific compiler selected for a language.
This may be a problem for users who link their library into Rust, but
is not a problem for the other direction.
To remove false warnings downgrade the message to STATUS.
If the wrong linker (language) is selected for Rust code, this should
also cause the link step to fail anyway, and the status should point in the right direction.
Closes #176
> Downgrade warning to status if no linker pref. is found

- cmake/Corrosion.cmake
In commit 27dbf8d "Replace build_crate.rs with cmake", I accidentally committed the code that is now removed here.
It was part of a workaround, that I figured out how to avoid, before
merging the commit (but forgot to remove this part of the code)
Closes #174
> Remove unused code

- cmake/FindRust.cmake
Some of the variables that corrosion provides for its users like
`Rust_VERSION<_MAJOR|_MINOR|_PATCH>` are only available when corrosion is installed and imported
via `find_package(Corrosion)`. This is because these variables are set as normal variables with
CMakes set() command, which limits their scope. When corrosion is imported via `add_subdirectory`,
these variables were only visible to corrosion, but not to the caller of `add_subdirectory`, which
is fixed by this commit.
> Fix usage of corrosion via add_subdirectory by promoting variables to CACHE

- cmake/Corrosion.cmake
- test/cpp2rust/CMakeLists.txt
This causes the OUTPUT_NAME target_property to be used when passing the
-l flag to corrosion_link_libraries. However, if any users have
corrosion_link_libraries(MyRustExe LibA) in their CMakeLists before the
target LibA is defined, it will now error out because the target is not
defined yet.
Fixes #172 
I'm not sure if this technically breaking change is ok. It definitely seems non-idiomatic to me to link against a library before it's been declared as a target, especially if you're going to set OUTPUT_NAME on it or other properties... but I can go back and wrap the get_property in an if(TARGET ${library}) if it's preferred.
> Respect OUTPUT_NAME when linking targets that have it defined

- cmake/FindRust.cmake
cargo on NixOS is not next to `rustc`, so it was previously not found.
To address this, we search for cargo in the regular way via
`find_program`, if the toolchain is not managed by rustup.
Closes #145
> Fix finding cargo on NixOS

- .github/workflows/test.yaml
- RELEASES.md
- cmake/CorrosionGenerator.cmake
- generator/src/subcommands/gen_cmake/target.rs
macos-10.15 is deprecated and will be removed at the end of next month
according to this announcement: https://github.blog/changelog/2022-07-20-github-actions-the-macos-10-15-actions-runner-image-is-being-deprecated-and-will-be-removed-by-8-30-22/
Use the newest available version macos-12 in github actions instead.
Additionally the MSRV is raised to 1.46, since apparently a change at crates.io surfaced an old cargo bug which was fixed in cargo 1.46.
> Use macos-12 in github actions

- cmake/Corrosion.cmake
- cmake/CorrosionGenerator.cmake
- cmake/FindRust.cmake
- generator/src/subcommands/gen_cmake.rs
- generator/src/subcommands/gen_cmake/target.rs
It's better to pass the arguments directly on the commandline.
This is a first step towards allowing the working directory for cargo
build to be set by the user, which would allow the user to use a
.cargo/config.toml themselves
> Don't generate .cargo/config

- test/rustflags/CMakeLists.txt
Corrosion selects Debug mode if Debug mode or nothing is specified and Release mode
for all other CMake build types.
This commit fixes the rustflags test for other build modes, where
Corrosion selected the release build mode for cargo.
Selecting a custom cargo profile will still cause issues for this test,
but there is not really a reason to do that when building corrosion,
so this can still be improved later.
> Fix Rustflags test

- .gitignore
- RELEASES.md
- cmake/Corrosion.cmake
- test/envvar/.cargo/config.toml
- test/envvar/CMakeLists.txt
- test/envvar/build.rs
The output directory (target-dir) is left unchanged.
Changing the cwd to the directory of the Manifest, has the advantage that
cargo can pick up `.cargo/config.toml` files in the source tree.
In the future this would also allow corrosion to respect `rust-toolchain.toml`
and other rustup toolchain overrides.
Closes #150
> Switch `cargo build` working directory to the Manifest (cargo.toml) directory

- CMakeLists.txt
- RELEASES.md
- cmake/Corrosion.cmake
- test/rustflags/CMakeLists.txt
- Allow explicitily setting a linker for when linking is done via cargo.
- Use `VERBATIM` option when invoking `cargo build` so that CMake quotes as necessary. This should improve the experience for passing some parameters, but is a breaking change.
Closes #133 
Closes #88
> Allow explicitly selecting the linker for a rust target

- cmake/Corrosion.cmake
Revert commit cb4e49e240d5c4d58b6117b426264121d8e1deac. When cross-compiling with clang it is necessary to manually add this flag. It appears that Rust does not add the flag for us. CI currently does not test clang + cross-compiling and it's not trivial to add without doubling the number of tests or reworking the github actions. Regression testing will be added in a future commit.
> Revert: Remove --target linker arg

- cmake/Corrosion.cmake
- cmake/CorrosionGenerator.cmake
- generator/src/subcommands/gen_cmake.rs
- generator/src/subcommands/gen_cmake/target.rs
- test/cpp2rust/lib2.cpp
- test/cpp2rust/rust/Cargo.lock
- test/cpp2rust/rust/Cargo.toml
- test/cpp2rust/rust/rust_dependency/Cargo.toml
- test/cpp2rust/rust/rust_dependency/src/lib.rs
- test/cpp2rust/rust/src/main.rs
Not setting `IMPORTED_LOCATION` on imported executables causes CMake
developer warnings. Setting `IMPORTED_LOCATION_<CONFIG>` is _not_ sufficient.
The issue only affects Multi-Config Generators like Ninja-MultiConfig or
Visual Studio, since otherwise `IMPORTED_LOCATION` is already always set.
For Multi-Config builds there is no "correct" thing to set
`IMPORTED_LOCATION` to, so we just always set it, and the last configuration
wins. This is not a problem since the more specific `IMPORTED_LOCATION_<CONFIG>`
variants are also set in the multi-config case.
> Always set IMPORTED_LOCATION 

- README.md
- RELEASES.md
- cmake/Corrosion.cmake
- test/custom_profiles/rust/Cargo.lock
- test/rustflags/CMakeLists.txt
- test/rustflags/rust/Cargo.toml
- test/rustflags/rust/some_dependency/Cargo.toml
- test/rustflags/rust/some_dependency/src/lib.rs
- test/rustflags/rust/src/lib.rs
For some scenarios it is better to not set Rustflags for all crates
in the dependency graph and instead only set it for the top-level
crate.
For example https://github.com/rust-lang/cargo/issues/8716
can be avoided in some scenarios by setting the rustflags via
rustc, which allows for faster rebuilds in such cases.
Note:
Switching to "cargo rustc" is slightly problematic in cases where a package has multiple crates (e.g. lib and one or more bins), however Corrosion doesn't actually support those cases right now anyway.
A follow-up PR will add support for multiple targets per package.
> Support "local" rustflags only affecting the main crate

- cmake/CorrosionGenerator.cmake
The results of target triple parsing are saved as properties of the workspace manifest fail.
Signed-off-by: Jonathan Schwender <schwenderjonathan@gmail.com>
> Fix target detection

- test/multitarget/CMakeLists.txt
- test/rust2cpp/CMakeLists.txt
- test/rust2cpp/rust/Cargo.toml
- To match rusts default relocation model, the foreign library should be compiled with -fPIE.
- add shared library to rust2cpp test
> Multitarget test

- cmake/Corrosion.cmake
- test/config/ParseTargetTriple/CMakeLists.txt
These targets may contain a dot in the arch field.
Closes #226
> Fix target-triple parsing for thumbv8m targets

- .github/workflows/test.yaml
Only test a minimum set a small matrix with the rust nightly toolchain.
The number of CI jobs are now 66 compared to 93 previously. There certainly is more optimization potential here, but removing this huge amount of nightly tests seems like a good starting point.
> CI: Reduce tested nightly combinations

- test/rustflags/CMakeLists.txt
- test/rustflags/cargo_config_rustflags/.cargo/config.toml
- test/rustflags/cargo_config_rustflags/CMakeLists.txt
- test/rustflags/cargo_config_rustflags/Cargo.toml
- test/rustflags/cargo_config_rustflags/src/main.rs
Add a test which checks if cargo picks
up rustflags set in `.cargo/config.toml` ( if the user project does not specify any global rustflags (RUSTFLAGS environment variable).
Closes #230
> Add test for Rustflags in .cargo/config.toml

- cmake/CorrosionGenerator.cmake
Check if the CMake target exists before adding a CMake target for a Rust crate.
This allows outputting a Warning with a helpful hint and to simply skip the target instead of outright failing.
Note: Only adding this warning for CMake >= 3.19 (using Corrosion Generator) for now.
Closes #228
> Warn if CMake target exists

- cmake/Corrosion.cmake
- test/gensource/gensource/CMakeLists.txt
- test/output directory/CMakeLists.txt
- test/output directory/output directory/CMakeLists.txt
The recent support for OUTPUT_DIRECTORY broke custom commands using
`POST_BUILD` and accessing build artifacts.
Add a dummy custom target with the existing name which depends on the
custom target. This ensures that `POST_BUILD` steps (on the internal
target) are done before the user facing target.
> Fix post build custom commands after OUTPUT_DIRECTORY support

- CMakeLists.txt
- RELEASES.md
- cmake/Corrosion.cmake
Remove previously deprecated functions.
The deprecations have been announced for a long time,
so it should be safe to remove these functions.
Removal is documented in Release notes.
> Remove deprecated functions and update Release notes

- RELEASES.md
- cmake/Corrosion.cmake
- cmake/FindRust.cmake
- Respect `QUIET` option to `find_package()`
- Improve respecting of `REQUIRED` option of `find_package()`
- Try to find suitable Rust version to satisfy  `VERSION` requirement of `find_package()`.  Previously, the version check would fail if the default toolchain did not match the version requirement.
- Add diagnostic, reminding the user to install target support via rustup if the target is not installed for the selected toolchain.
- Remove unused `CARGO_RUST_FLAGS`. 
Closes #224
> Various FindRust improvements

- cmake/Corrosion.cmake
- test/output directory/CMakeLists.txt
- test/output directory/output directory/CMakeLists.txt
- test/output directory/output directory/consumer.cpp
Previously, the properties were read from the wrong target. The IMPORTED_LOCATION property needs to be set on the internal target, but the OUTPUT_DIRECTORY properties set by the user will be set on the user facing target (without -static or -shared suffix).
Closes #240
> Read OUTPUT_DIRECTORY properties from main library target

- CMakeLists.txt
Bump the version number.
Cmake doesn't seem to support postfixes such as alpha or beta otherwise I would add one.
> Prepare for the next Release

- .github/workflows/test.yaml
- cmake/Corrosion.cmake
- Replace undocumented `cmake -H` option with `cmake -S`, since `-H` is aliased with `--help` on more recent cmake versions.
- Use the default shell in CI where possible, which means powershell on windows. This is required because git bash [does not work](https://github.com/marketplace/actions/enable-developer-command-prompt#name-conflicts-with-shell-bash) with the `msvc-dev-cmd` action we need for msvc. 
- Use Yaml `>`  syntax to replace line continuations with spaces for long commands. Powershell line continuation is space +  backtick, so we can't just use `\`.
> Fix windows-latest CI issues

- .github/workflows/test.yaml
See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Closes #233
> Convert CI step outputs to new syntax

- cmake/Corrosion.cmake
Setting LIBRARY_PATH on macos 13 causes issues when compiling rust
crates with rust dependencies compiling modern C++ in their build script.
This can be reproduced without Corrosion by running:
```
LIBRARY_PATH=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib \
cargo rustc --lib --package cxxbridge-crate --manifest-path \
/path/to/cxxbridge/rust/Cargo.toml  -- -Cdefault-linker-libraries=yes
```
Without LIBRARY_PATH the build completes without problems, but with the
environment variable set the build script errors, since the C++ code
contains e.g. C++11 extensions.
Since on macos-13 everything works fine when removing LIBARY_PATH remove
it for macos 13, but keep it for previous macos versions.
> Do not set LIBRARY_PATH on macOS 13

- .github/workflows/test.yaml
- cmake/Corrosion.cmake
If cxxbridge is not installed, or the version does not match the cxx version used in the rust crate, then
compile the correct cxxbridge version.
This is done once per required version.
> Build cxxbridge if necessary

- cmake/Corrosion.cmake
- cmake/CorrosionGenerator.cmake
- generator/src/subcommands/gen_cmake.rs
- generator/src/subcommands/gen_cmake/target.rs
MSVC abi may be used independently of the MSVC generator. MSVC uses cl.exe, so we can't use
the compiler as the linker driver.
We continue to just ignore MSVC in this case and let cargo / rust decide on the linker on its own.
> Don't set linker for MSVC abi

- cmake/Corrosion.cmake
- test/CMakeLists.txt
- test/ConfigureAndBuild.cmake
- test/workspace/workspace/CMakeLists.txt
Manually appending the configuration type may make
loading of shared libraries fail at runtime.
To prevent this, we let CMake postfix the Generator
configuration type.
> Fix Multi-Config Generator default output directory

- .github/actions/setup_test/action.yaml
- .github/scripts/determine_compiler.sh
If the option is not given, we still choose a suitable default for the platform. If the option is given, then we set the compiler based on the input.
This commit also fixes CMAKE_SYSTEM_NAME, which should now be always
set manually when cross-compiling.
> CI: Add option to choose compiler

- cmake/Corrosion.cmake
- cmake/CorrosionGenerator.cmake
- generator/src/subcommands/gen_cmake/target.rs
As discussed in issue #270 we at least should not set the linker for Rust static libraries. In the general case the linker is not needed for static libraries, and if it is invoked,
Rust should take care of what to choose
(e.g. for building build scripts) instead
of us forcing the choice.
> Don't set linker for Rust static libraries

- .github/actions/setup_test/action.yaml
Speed up CI by caching the .cargo registry.
This turns out to be _much_ faster than letting cargo update the cargo index/registry on first access.
> CI: Cache cargo registry

- .github/actions/setup_test/action.yaml
We don't need to install g++ if we are compiling
for x86_64, since the host g++ is already pre-installed.
> CI: Only run apt-update when necessary

- .github/workflows/test.yaml
- test/CMakeLists.txt
- test/custom_profiles/CMakeLists.txt
The initial configure for MSVC is quite slow, so we cache the build directory since reconfiguring is faster.
> CI: Cache MSVC build directory

- generator/Cargo.lock
```
Updating cargo_metadata v0.15.0 -> v0.15.2
Updating itoa v1.0.3 -> v1.0.5
Updating proc-macro2 v1.0.43 -> v1.0.49
Updating quote v1.0.21 -> v1.0.23
Updating ryu v1.0.11 -> v1.0.12
Updating semver v1.0.13 -> v1.0.16
Updating serde v1.0.144 -> v1.0.151
Updating serde_derive v1.0.144 -> v1.0.151
Updating serde_json v1.0.85 -> v1.0.91
Updating syn v1.0.99 -> v1.0.107
Adding thiserror v1.0.38
Adding thiserror-impl v1.0.38
Updating unicode-ident v1.0.3 -> v1.0.6
Updating unicode-width v0.1.9 -> v0.1.10
```
> Update legacy generator dependencies

- cmake/Corrosion.cmake
Use the target parameter for "cargo clean" as for build.
> Fix clean target when cross-compiling

- cmake/Corrosion.cmake
- test/gensource/gensource/CMakeLists.txt
Add a convenience function to parse the package version from the package manifest (Cargo.toml). This is mainly intended for code generators written in Rust, so that downstream users can easily check if an installed version of the code generator is up to date with the version specified in the package manifest. Users could then decide to rebuild from source if the installed version is outdated and otherwise use the installed version.
> Add convenience function to parse package version from Cargo.toml

- .github/workflows/test.yaml
- bors.toml
Using bors allows easy configuring of more required statuses for the final merge (bors r+).
> CI: add bors bot

- CMakeLists.txt
- RELEASES.md
- cmake/Corrosion.cmake
- cmake/FindRust.cmake
Corrosion itself does not need to enable any languages. If linking is done via Rust, then rust will by default use a target specific linker e.g. cc or rust-lld.
If C++ is used then this is not sufficient, but then the user will also have turned on C++ as a language of their project.
If linking is handled by CMake, then it is also the responsibility of the user to enable a language,
otherwise they couldn't compile any code anyway.
> Remove `enable_language()`

- README.md
- RELEASES.md
- cmake/Corrosion.cmake
- cmake/CorrosionGenerator.cmake
This PR adds new `IMPORTED_CRATES` flag to `corrosion_import_crate()` to retrieve the list of imported crates in the current scope. Idea was from issue #218.
With this PR, this kind of operation is made possible.
```cmake
corrosion_import_crate(MANIFEST_PATH ../native/Cargo.toml IMPORTED_CRATES crates_list)
target_link_libraries(${BINARY_NAME} PRIVATE ${crates_list})
```
I checked that this works as intended in an actual Rust/C++ project.
> Add parameter to corrosion_import_crate to return list of added targets

- cmake/Corrosion.cmake
- cmake/CorrosionGenerator.cmake
Follow-up PR to #312.
Currently, the option is not supported with the old generator. It could be backported if someone needs it, but this isn't a priority.
Also properly pass through intermediate parameter names to pass back the list up the callchain.
> Output Error if IMPORTED_CRATES is selected with CORROSION_NATIVE_TOOLING

- README.md
The directories got moved at some point, so the links broke in the README.
> Fix links to rust2cpp code in README

- .github/workflows/test.yaml
The final job should now always produce a status of either success or failure.
> CI: improve status check job.

- cmake/Corrosion.cmake
The regex to determine the name of the actual library target tries to strip the -static or -shared suffix did not allow for dashes in the name. Since the regexp closes with a $, the suffix should only match at the very end and we can allow any character before the last dash.
Fixes #321
> Fix imported location target property when target contains dashes and CORROSION_RESPECT_OUTPUT_DIRECTORY is true

- CMakeLists.txt
- README.md
- RELEASES.md
The v0.3 branch diverges from the master branch and does not carry all changes, so we need to update the changelog.
> Add v0.3.3 Release notes

- RELEASES.md
- cmake/Corrosion.cmake
- cmake/FindRust.cmake
This allows e.g. using the nightly toolchain for only one target
These are experimental options for now and could be changed or removed before a stable release
> Allow user to override rustc/cargo per target

- .github/actions/setup_test/action.yaml
- .github/workflows/test.yaml
cxxbridge-cmd internally uses clap and liberally increases its MSRV so, we just test stable-2 in CI.
> CI: Use stable-2 toolchain for cxxbridge

- .github/workflows/test.yaml
Only run the cxxbridge tests in this job.
We test it seperately, since cxxbridge has a higher overhead than the other jobs, due to the necessary caching / installation of the cxxbridge-cmd tool.
In the future all bindings tests could be in this matrix.
> CI: Reduce cxxbridge job runtime

- cmake/CorrosionGenerator.cmake
- generator/src/main.rs
We do not care about non-workspace dependencies at all. This prevents cargo metadata from fetching from the network when it is not needed at all and also makes it do less work in general.
> Pass --no-deps to cargo metadata

- cmake/Corrosion.cmake
Fixes a case where a target which should be built for the host platform, erroneously got a linker flag instructing clang to link for the cross-compile target.
> Fix hostbuild with clang

- cmake/Corrosion.cmake
Alpine uses a separate vendor for Rust installed from aports: `$CARCH-alpine-linux-musl`
See https://gitlab.alpinelinux.org/alpine/aports/-/blob/329ba719/community/rust/alpine-target.patch
> Add "alpine" as a known triple vendor

- .github/workflows/test.yaml
- test/CMakeLists.txt
Fixes an issue of CI runs being marked as passed,
when the script actually failed.
This is because `pwsh` apparently doesn't by default have a mode akin to `set -e` on bash.
> CI: Use powershell on windows

- doc/src/SUMMARY.md
- doc/src/common_issues.md
It's probably useful to document some common issues people encounter when linking Rust with C/C++ code and the other way around.
> Document msvcrt linking issues.

- .github/workflows/test.yaml
- doc/src/common_issues.md
- test/cxxbridge/CMakeLists.txt
- test/cxxbridge/cxxbridge_cpp2rust/CMakeLists.txt
- test/cxxbridge/cxxbridge_rust2cpp/CMakeLists.txt
- rust bins require the C++ code to be built with non-debug versions of msvcrt.
- C++ bins can use the debug version.
> Fix cxxbridge test on windows MSVC

- cmake/Corrosion.cmake
Assume the global RUSTFLAGS environment variable is targeted at the actual build targets and not at Corrosion's own build-time codegen to work around issues that break corrosion-generator compilation.
(Context: building w/ RUSTFLAGS='-Zsanitizer=address' set requires invoking cargo w/ `--target <triple>` for compilation to succeed or else linker errors will block compilation from completing successfully. If set as a global environment variable outside of CMake, it will break the build of corrosion-generator).
> Prevent RUSTFLAGS from breaking Corrosion's own build-time code

- cmake/Corrosion.cmake
Our `$CARGO_EXECUTABLE` is always a resolved cargo bin and never a
rustup proxy. This has the side-effect that cargo(rustup) will not
set the `RUSTUP_TOOLCHAIN` environment variable (since rustup is never
invoked).
This in turn leads to problems, since the `RUSTC` env variable cargo
exposes to  buildscripts is a `rustup` proxy, and needs to be, because
some buildscripts expect `$RUSTC` to be a rustup proxy.
The missing `RUSTUP_TOOLCHAIN` from before now leads to `$RUSTC`
invocations from buildscripts respecting the `rust-toolchain.toml`
files potentially present in the crate with the buildscript (which
can be a downstream dependency of us).
Since the toolchain tomls can contain required rust compenents, this
leads to rustup suddenly starting to install rust components, which
are only …
> Set CARGO_BUILD_RUSTC when building the Legacy Generator

- cmake/Corrosion.cmake
- doc/src/SUMMARY.md
- doc/src/ffi_bindings.md
- test/cbindgen/rust2cpp/CMakeLists.txt
- Add documentation
- Fix the dependency rules
- Add header to header fileset on CMake 3.23
- rename `CRATE` parameter to `TARGET` to hint that ideally this should be an imported CMake target.
There is still some work remaining before releasing this in a tagged version, but this should already be an improvement.
> Improve the cbindgen integration

- cmake/Corrosion.cmake
Downgrade the log-level to DEBUG for the message informing the user of missing values for a keyword that requires values. Passing no values after a keyword may be common in user-code since it simplifies the usercode.
It may still a sign that something went wrong on the user side, so we do want to log it. Users investigating problems will then see the output with the DEBUG log-level enabled.
Closes #356
> Downgrade log-level for potentially erroneous arguments

- cmake/Corrosion.cmake
- cmake/CorrosionGenerator.cmake
- generator/src/subcommands/gen_cmake.rs
- generator/src/subcommands/gen_cmake/target.rs
We now have access to a list of imported crates
in `corrosion_import_crate`, so
instead of passing through arguments like
FEATURES, PROFILE and FLAGS to `_add_cargo_build`
it is much simpler to simply initialize the per-target properties from corrosion_import_crate.
The user can still override these per crate as usual, this simply removes a lot of code which becomes redundant, if you only read from the target property instead of additionally having a pass-through option to consider.
> Simplify Argument handling

- .github/workflows/test.yaml
- cmake/Corrosion.cmake
- cmake/FindRust.cmake
- test/cpp2rust/cpp2rust/rust/build.rs
- test/parse_target_triple/CMakeLists.txt
- test/parse_target_triple/parse_target_triple/CMakeLists.txt
- test/parse_target_triple/parse_target_triple/Cargo.toml
- test/parse_target_triple/parse_target_triple_should_fail/CMakeLists.txt
- test/parse_target_triple/parse_target_triple_should_fail/Cargo.toml
- test/rust2cpp/rust2cpp/rust/build.rs
Corrosion selects a default linker to ensure builds work as expected. This is required to support:
- Linking C++ libraries (i.e. including the c++ stdlib)
- Select a correct linker for cross-compiling.
Instead of relying on CMake implementation details, we now:
- select the C++ compiler for targets where C++ is linked into. Previously we used the C++ compiler if C++ was enabled as a language
- Assume that the C language is enabled if C++ is not.
> Cleanup Linker selection code

- generator/Cargo.lock
- generator/Cargo.toml
syn increased it's MSRV to 1.56, and cargo metadata pulls it in indirectly raising our MSRV for the
legacy generator.
To avoid this we specify the max versions of thiserror and serde.
This will need to get backported to the release branch
> Fix generator build on Rust versions pre 1.56

- CMakeLists.txt
- README.md
- RELEASES.md
- generator/Cargo.lock
- generator/Cargo.toml
Fixes building on older Rust toolchains after upstream MSRV breakage in minor release.
> Release v0.3.5

- cmake/Corrosion.cmake
- test/cxxbridge/CMakeLists.txt
- test/cxxbridge/cxxbridge_cpp2rust/CMakeLists.txt
- test/cxxbridge/cxxbridge_cpp2rust/cpplib.cpp
- test/cxxbridge/cxxbridge_cpp2rust/rust/src/main.rs
Generate `rust/cxx.h` in addition to the per target header.
> Improve cxxbridge integration

- cmake/Corrosion.cmake
This fixes an issue where using `corrosion_add_cxxbridge` on a system that doesn't have cargo in PATH fails with "Crate ... does not depend on cxx"
> Fix cargo tree to use the correct cargo executable

- cmake/Corrosion.cmake
This is not catched by tests in macos because the tests are setting `CMAKE_CXX_STANDARD`.
https://github.com/corrosion-rs/corrosion/blob/e516737bf4987d000353045133c2f82b23553490/test/cxxbridge/cxxbridge_cpp2rust/CMakeLists.txt#L4-L5
Default compilation on macos fail, if `CMAKE_CXX_STANDARD` is not set.
> cxxbridge: set `cxx_std_11` as PUBLIC compile feature

- RELEASES.md
- cmake/Corrosion.cmake
- cmake/FindRust.cmake
- doc/src/usage.md
Instead of hand maintaining a list of required libraries, it is more efficient to just ask `rustc` what libraries are needed to link.
Using a demo project will not give a full list, but at least a minimum list of required dependencies - which is the same situation as now.
In the future we could expand this by passing arguments from the cargo build step to the link-step via a file.
But that needs more investigation, so we do this improvement first.
> Improve required library detection for staticlibs

- cmake/FindRust.cmake
If binary directory is in workspace, printing libraries will fail.
Adding `[workspace]` to Cargo.toml fixes that besides this patch also fixes a typo.
> Fix determining required link libraries

- cmake/Corrosion.cmake
Add the actual CMake version and the path to the used cmake version to the error message. The CMake version used by the user could be e.g. a bundled CMake version, which may not be obvious to the user. Printing the path to the used CMake executable should make such cases obvious.
> Improve Multi-Config error message

- cmake/Corrosion.cmake
Sorry, I added this code (in https://github.com/corrosion-rs/corrosion/pull/373) in order to fix an error with `cargo` not being found when it is not in path, but it seems that my patch was not good enough as it now fails because cargo can't find `rustc`... I think this patch makes it work (I can only test this locally because the github CI seems to have the Rust installation configured in PATH)
> Fix cargo tree to use the correct rustc executable

- .github/FUNDING.yml
- .github/ISSUE_TEMPLATE/bug_report.yml
- Add an issue template, which should encourage users to provide a configure log, or at least detailed information for bugs.
- I haven't tried this before so we may need to iterate over this
- Also add a funding.yml for github sponsers while I'm at it.
> Add an issue template

- cmake/Corrosion.cmake
When the linker is invoked via Rust, and set to `clang` or a different compiler that requires a target parameter, the --target parameter must be passed, otherwise the host linker could be invoked.
The condition checkingt his was wrong, because CMake evaluates quoted strings to false, unless the content is explicitely one of the true values. We need to use the unquoted variable instead in order to have the desired behavior of checking if the compiler target variable is set.
> Fix passing target when linking via clang

- cmake/FindRust.cmake
- doc/src/usage.md
- test/find_rust/CMakeLists.txt
- test/find_rust/rustup_proxy/CMakeLists.txt
Hey, I've implemented it as we discussed last week :)
This should work when running with all arguments empty (if `Rust_RUSTUP` is found in the home directory), and also in setups where rustup is not in the standard location if the user points `Rust_COMPILER` to the `rustc` proxy binary.
Should this new argument also be added to the `_Rust_USER_VARS` list and the list that's passed to `find_package_handle_standard_args`? I didn't quite understand what they're for.
> Add option to compile with the rustup proxy binaries

- cmake/Corrosion.cmake
Fix building the generator on older Rust toolchains.
> Use lockfile for legacy generator

- CMakeLists.txt
- cmake/FindRust.cmake
Do not rely on cargo new generating a valid Cargo.toml or valid package and instead ship everything we need ourselves.
> Refactor detecting required link libraries

- .github/workflows/test.yaml
- RELEASES.md
- cmake/Corrosion.cmake
- Fix the PROFILE option for the legacy Generator
- Additionally test old CMake versions with the newest stable Rust version in CI (which catches the issue)
> Fix the PROFILE option with old CMake versions

- .github/workflows/test.yaml
- .github/workflows/test_legacy.yaml
- CMakeLists.txt
- cmake/Corrosion.cmake
- generator/CMakeLists.txt
- generator/Cargo.toml
- generator/Compat.Cargo.lock
- generator/Compat.Cargo.toml
- Reproduce issue 428 by testing the legacy Generator + nightly Rust in CI.
- Refactor the CMake code for building the legacy Generator into a subdirectory
- Select a Cargo.toml / Cargo.lock for the legacy Generator depending on the Rust version
> Fix Legacy CMake Generator with nightly Rust

- generator/Cargo.lock
- generator/Cargo.toml
Pin serde to the last release before downloading binaries was introduced.
This is only relevant for the legacy generator and does not affect users that are not using the legacy generator.
> Legacy Generator: Pin Serde to 1.0.171

- .github/workflows/gh-pages.yaml
The artifacts were mistakenly copied into v0.4/books instead of directly into the v0.4 directory, which broke the links.
> Fix v0.4 GH pages

- cmake/FindRust.cmake
On [Chimera Linux](https://chimera-linux.org/) the target triple of the packaged Rust compiler is `<arch>-chimera-linux-musl`. This PR adds `chimera` to the known vendors to address this warning:
```
CMake Warning at cmake/FindRust.cmake:113 (message):
Failed to parse target-triple `x86_64-chimera-linux-musl`.Corrosion
determines some information about the output artifacts based on OS
specified in the Rust target-triple.
```
> Add "chimera" as a known triple vendor

- cmake/FindRust.cmake
`x86_64-unikraft-linux-musl` was added in Rust 1.73
> Add unikraft to known vendors

- cmake/Corrosion.cmake
- cmake/CorrosionGenerator.cmake
- Defer the determination of whether to apply a .exe suffix for the byproduct copying and imported location setting if possible
- Determine the .exe suffix first based on the existence of the hostbuild property and then fall back Rust_CARGO_TARGET_OS
> Fix support for hostbuild executables when cross-compiling to non-windows on windows hosts

- cmake/Corrosion.cmake
- Set the `AR_<triple>` variable for cc-rs.
- Simplify condition for CC_<triple> and CXX_<triple>. The target is always defined in corrosion, so there is no need to check if it set.
Closes #454
> Set AR_<triple> for cc-rs

- RELEASES.md
- cmake/Corrosion.cmake
The native tooling was removed, so remove the option.
> Remove useless CORROSION_NATIVE_TOOLING option

- cmake/Corrosion.cmake
Remove the option to turn off support for OUTPUT_DIRECTORY. Corrosion's minimum supported CMake version is high enough to always have the CALL DEFER feature, which allows us to remove the legacy code-path. There is no point in keeping the legacy code path, since users can just unset the relevant variables, if they don't want Corrosion to copy artifacts.
> Always respect OUTPUT_DIRECTORY

- CMakeLists.txt
Use `PROJECT_IS_TOP_LEVEL` where possible and remove unused options.
> Minor Cleanup

- CMakeLists.txt
While creating the Vcpkg port, I discovered that the CMake script tries to include the tool during the build process immediately after a note recommending that users **not** do this. To create the Vcpkg port, I cannot have Rust available. To resolve this, I need to optionally disable the include as it is recommended.
> fix: add a check to include, default to no change in actions

- cmake/Corrosion.cmake
The value of the `_CORROSION_VERBOSE_OUTPUT_FLAG` variable (set based on the `CORROSION_VERBOSE_OUTPUT` option) isn't propagated to the `_add_cargo_build` function where it is used: https://github.com/corrosion-rs/corrosion/blob/0a3bdf452995803c334d79dc9a2affbfad51b720/cmake/Corrosion.cmake#L768 Setting it as cache entry fixes that.
> Set `_CORROSION_VERBOSE_OUTPUT_FLAG` as cache entry

- .github/workflows/linux.yaml
- .github/workflows/test.yaml
- .github/workflows/visual_studio.yaml
- bump actions/cache to v4
- Use lukka/get-cmake instead of corrosion-rs/install-cmake. This fixes deprecation warnings in CI due to
the deprecation of node16.
> CI: Update actions to use node20

- cmake/Corrosion.cmake
Do not forward the PROFILE argument from `corrosion_import_crate` to `_generator_add_cargo_targets`.
Closes #495.
> corrosion_import_crate: Fix PROFILE argument in combination with CRATES

- .github/actions/setup_test/action.yaml
- .github/workflows/gh-pages.yaml
- .github/workflows/test.yaml
- .github/workflows/test_legacy.yaml
applies changes from 6e2740fb3d817bb0422a579ac542471f59af7cfb and 366066c9caed822a4cbfc2fafbf7d0116d59b832
to the stable/v0.4 branch.
> ci: bump actions to avoid deprecation notice

- RELEASES.md
- cmake/Corrosion.cmake
- doc/src/advanced.md
If a user tries to use `corrosion_link_libraries` on static libraries, forward the dependencies to C/C++ consumers by internally calling `target_link_libraries()`.
> corrosion_link_libraries: Forward static libraries dependencies

- cmake/CorrosionConfig.cmake.in
Description:
Currently the cmake export `CorrosionConfig.cmake` adds a hardcoded path (`CMAKE_INSTALL_FULL_DATADIR`) to `CMAKE_MODULE_PATH`. Unfortunately this path is only valid during build time of corrosion. 
If the resulting package is shipped (e.g. via a package manager like conan), then the path and therefore also the corrosion package becomes invalid. 
Solution:
Instead, the import prefix of the package (`PACKAGE_PREFIX_DIR`) is used.
> cmake export (find_package) becomes portable

- RELEASES.md
- cmake/Corrosion.cmake
- `cbindgen` considers the `TARGET` environment variable when generating bindings, so we should set the target we are compiling for.
> cbindgen: Pass Rust target-triple to cbindgen

- RELEASES.md
- cmake/Corrosion.cmake
- cmake/FindRust.cmake
As of https://github.com/rust-lang/rust/pull/122268, rust emits /defaultlib:msvcrt in native-static-libs
This ends up in INTERFACE_LINK_LIBRARIES, and then ninja thinks it's a file:
ninja: error: '/defaultlib:msvcrt', needed by 'cpp-exe.exe', missing and no known rule to make it
This check to see if libraries start with a slash, and then assuming that they are a flag, and putting those in INTERFACE_LINK_OPTIONS instead. If there is some better way to detect flags, I'm all for it. We could also have it have anything that starts with `-` but not start with `-l` be detected as a flag, but that seems a bit more likely to be disruptive.
I checked commandlines and it does indeed get propaged properly to the commandline.
> msvc: handle flags that come from native-static-libs

- .github/workflows/gh-pages.yaml
- CMakeLists.txt
- README.md
- RELEASES.md
- doc/src/introduction.md
- doc/src/quick_start.md
- doc/src/setup_corrosion.md
Corrosion changes slowly enough, that I think it makes sense to make an 1.0 release.
CMake doesn't support any modifiers like `-alpha`, so we just take 0.99 instead.
We want to leave room for further breaking releases in the legacy version.
> Bump the version number to 1.0-pre-release

- cmake/Corrosion.cmake
- cmake/CorrosionGenerator.cmake
- generator/src/subcommands/gen_cmake/target.rs
- test/output directory/CMakeLists.txt
- test/output directory/output directory/CMakeLists.txt
Make a best effort with old CMake versions to respect output directories. We can't know which properties the user might set or change **after** the crates are imported, but we can respect the `CMAKE_<XYZ>` variables which are set **before** the crates are imported.
> Legacy CMake: Respect `CMAKE_<XYZ>_OUTPUT_DIRECTORY`

- cmake/Corrosion.cmake
- cmake/CorrosionGenerator.cmake
Create the main CMake targets earlier, so we can
set target properties on them early in the generator, so we can use them later on during configuration.
We don't strictly need this right now, but it reduces the diff to the stable/v0.5 branch and being able to set properties earlier is something that seems like it will be useful.
> Create CMake targets earlier

- cmake/Corrosion.cmake
`CARGO_PACKAGE` was added in #452 to work around the package name and crate name (potentially) being different.
Since b11a33 corrosion saves the package name as a target property, which we can use in `corrosion_experimental_cbindgen`. This allows us to remove the `CARGO_PACKAGE` parameter.
> cbindgen: Remove CARGO_PACKAGE parameter

- cmake/FindRust.cmake
The macro _find_rust_failed is not called from inside any functions in FindRust. Find modules are `include`d, so variables need to be set in local scope (which was already done in the successfull case).
Fixes #527
> Fix FindRust setting Rust_Found=false in wrong scope

- cmake/FindRust.cmake
The macro _find_rust_failed is not called from inside any functions in FindRust. Find modules are `include`d, so variables need to be set in local scope (which was already done in the successfull case).
Fixes #527
(cherry picked from commit 58d83f0c21c3dcde39ce60079ba5d901aafe7acc)
> Backport: Fix FindRust setting Rust_Found=false in wrong scope

- cmake/FindRust.cmake
It's difficult for Corrosion to correctly choose the right msvcrt version. CMake has a target property for it, and we also don't know which build configurations the user CMake code expectes to be Debug related.
The previous code actually already removed the linking against `msvcrt` in all cases except "Debug" builds. This was not intentional, but indicates that removing the library entirely from the link list, and leaving it up to the C/C++ code to link it in, should work well in practice.
> Leave choosing `msvcrt` up to the C/C++ CMake code

- cmake/Corrosion.cmake
- doc/src/quick_start.md
- doc/src/usage.md
Works on #415 and #63.
This only installs the actual library file(s) and not extras such as headers.
Not tested on Windows for compatibility with import library files for shared libraries.
I moved the function definition out to be used as an anchor so it could be used for docs without modifying it, since I'm not entirely sure what the planned feature set of it is going to be.
> Make corrosion_install work for library files and update docs

- .github/workflows/test.yaml
- cmake/FindRust.cmake
rustup can be installed from a package manager.
If Rust_RESOLVE_RUSTUP_TOOLCHAINS is set to OFF, but rustup is
installed, we can't assume rustc will be next to rustup.
> Fix finding rustc with rustup from package manager when Rust_RESOLVE_RUSTUP_TOOLCHAINS=OFF

- cmake/Corrosion.cmake
cxxbridge path without extension may break incremental build.
```txt
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(254,5): warning MSB8065: Custom build for item "D:\rs-build\build\windows\x64\CMakeFiles\bc3d63f434567f4c249906ffad608cc1\cxxbridge.rule" succeeded, but specified output "d:\rs-build\build\windows\x64\corrosion\cxxbridge_v1.0.124\bin\cxxbridge" has not been created. This may cause incremental build to work incorrectly. [D:\rs-build\build\windows\x64\runner\cxxbridge_v1.0.124.vcxproj]
```
> Fix: add extension to cxxbridge path

- cmake/Corrosion.cmake
Sorry for the immediate do over, but it seems there were a few mistakes in my last PR #544.
It seems the else was accidentally put on the check for a `TARGET ${TARGET_NAME}-static` lib instead of the `TARGET_TYPE STREQUAL *`.
Additionally, I forgot to put a guard on the `file(APPEND)` statements, so every reconfigure would add yet another set of `add_library`s for both static/shared, leading to it not working.
I'm not sure what the correct solution for this is, but the current solution at the very least works.
> corrosion_install: fix reconfiguring breaking EXPORTs

- .github/scripts/toolchains/x86_64-pc-windows-gnu-clang.cmake
- .github/scripts/toolchains/x86_64-pc-windows-gnullvm.cmake
- .github/workflows/test.yaml
- CMakePresets.json
- cmake/Corrosion.cmake
List of problems / fixes related to gnullvm:
> Fix gnullvm and test gnullvm with msys2 in CI

- .github/workflows/test.yaml
- CMakePresets.json
- cmake/FindRust.cmake
Followup to #511 but adding support for GNU-style clang flags. 
The condition is really CMAKE_CXX_COMPILER_FRONTEND_VARIANT==GNU && CMAKE_CXX_LINK_EXECUTABLE starts with ${CMAKE_CXX_COMPILER}, but they are always set together, and I doubt cmake would change that. 
For msvc frontends, cmake directly invokes the linker so the passing the flags verbatim is still what we want to do.
> clang,windows: fix passing link flags when using clang in GNU frontend mode on windows

- cmake/Corrosion.cmake
`rustc` always targets the earliest deployment platform version possible for Rust code, but the `cc` crate defaults to the host's SDK version which is typically very recent.
When the CMake uses a toolchain that has its' own minimal supported macOS version (for example Qt), this leads to linker errors and possible crashes when deploying to older yet supported systems.
> Propagate Apple deployment target version from CMake to `cc`

- cmake/Corrosion.cmake
I'm currently using CXX with Corrosion on a project that is rather difficult to build outside of a docker container and also takes a long time to build.
To get good IDE completion with clangd however, clangd needs to be able to access the header files that are generated by CXX.
This PR allows users to specify a custom CMake target that will regenerate the cxx bridges without needing to recompile.
That way, I can get good IDE completion without having to have a fully working build setup in and outside my docker container.
> corrosion_add_cxxbridge: Add target to regenerate bridge files

- .github/workflows/visual_studio.yaml
This breaks when the msvc version in the runner image gets updated. If we could figure out the location / version of the selected msvc toolchain, we could add the toolchain to the cache key.
> CI: Stop caching the msvc build dir

- cmake/Corrosion.cmake
Adds a flag which allows not passing the `USES_TERMINAL` option to custom targets that corrosion creates.
This prevents cargo from detecting the terminal, and e.g. prevents the default colored output, but allows reducing verbosity when doing quiet builds.
Closes #583
> Add NO_USES_TERMINAL option

- RELEASES.md
- cmake/Corrosion.cmake
- doc/src/usage.md
- test/cbindgen/rust2cpp/CMakeLists.txt
- Use `--locked` to avoid potential issues with dependencies.
- Add CORROSION_TOOLS_RUST_TOOLCHAIN option: This allows users to choose a different rust toolchain
to compile build-tools use by corrosion (currently cbindgen and cxxbridge)
> Fix cbindgen CI test failures

- cmake/FindRust.cmake
Closes #590 by applying the following mapping:
| Variable \ Rustup ver. | v1.27.1      | v1.28.0                            |
|------------------------|--------------|------------------------------------|
| `$_TOOLCHAIN_OVERRIDE` | `(override)` | `(active)`                         |
| `$_TOOLCHAIN_DEFAULT`  | `(default)`  | `(default)` or `(active, default)` |
Corrosion would like to find out the path for the active toolchain via `rustup toolchain list --verbose` from the toolchains marked `(override)` and/or `(default)`: if `(override)` is present, then it's active, otherwise `(default)` would be active:
https://github.com/corrosion-rs/corrosion/blob/b88ec09915a6b12d1aaec7e451ecf0e41a831030/cmake/FindRust.cmake#L423-L428
In rustup v1.28.0 beta (or …
> fix: update `FindRust` to work with rustup v1.28.0

- cmake/Corrosion.cmake
The dependency on cxx may be gated behind a feature. We can simply enable all features for dependency resolution though.
cxxbridge-cmd also only appears with --target all so we enable all targets.
We start preferring `cxxbridge-cmd`, since that was recommended by dtolnay.
We still fallback to parsing the version of `cxx` to support older cxx versions, where the bridge version may not appear in the dependency tree.
In practice this fallback shouldn't cause any problems, since we anyway need to ensure that
`cxxbridge version == cxx version`.
> cxx: Consider Rust target and features

- cmake/Corrosion.cmake
Issue #612 reported that the MSVC compiler on windows does not support long paths. In an a first attempt to reduce the impact we remove unnecessary parts from the build directory name.
> Adjust default build directory

- cmake/Corrosion.cmake
PATH may be different at build time, so cargo might not be in PATH, which would cause cbindgen to fail.
We point cbindgen to the correct CARGO executable explicitly instead.
> cbindgen: Fix rare issue with cbindgen failing to find cargo

- .github/workflows/test.yaml
- CMakeLists.txt
- cmake/Corrosion.cmake
It seems that previously `cbindgen` was preinstalled on some runner images. Now that doesn't seem to be the case anymore, which is causing CI failures.
The remaining CI issue is that the latest cbindgen version requires a newer rust version to install than we test in CI.
I believe this is already fixed in main, but we ignore this issue on the stable branch, since it is not critical.
> Partially fix CI of stable/v0.5 branch
